### ISSUE TITLE
Missing contributors on About page

### ISSUE THREAD

**Issue by willingc** [nteract/nteract.io#101]
It looks like the About page isn't displaying the full alpha list of contributors (contributors with gh user names >= 's')

Or maybe I've been demoted :wink:

**Comment by captainsafia** [comment]
Bummer. We’re using the GH API for this so it might have changed.

**Comment by willingc** [comment]
I think @rgbkrk may have bumped the script recently. I can take a look but I don't know where the script lives :(

**Comment by captainsafia** [comment]
It's under @rgbkrk's org here:  https://github.com/rgbkrk/nteract-members

**Comment by rgbkrk** [comment]
Wow that's no good. I would love to switch off my current script which is a two fetch operation for what should be a smaller query. We should switch it over to a github graphql query that we have automated to run before deploy.

**Comment by lgeiger** [comment]
I'm happy to revisit #31
