### ISSUE TITLE
Include Scala on /kernels page

### ISSUE THREAD

**Issue by rgbkrk** [nteract/nteract.io#13]
We should include a Scala kernel on the https://nteract.io/kernels page.

/cc @alexarchambault -- What could we put in the install lines like we do for Python, R, etc.?

**Comment by alexarchambault** [comment]
Something like
```
$ curl -sL https://git.io/vypsS | bash
```
or
```
$ curl -sL https://raw.githubusercontent.com/alexarchambault/jupyter-scala/master/jupyter-scala | bash
```
should do.

I haven't succeeded in using the kernel from nteract itself though (both on OS X and linux)... But it's fine from hydrogen.

**Comment by rgbkrk** [comment]
Strange that it works from Hydrogen but not nteract, it's the same node.js code for spawning kernels. ¯\\\_(ツ)\_/¯ I used jupyter-scala in nteract before using it in Hydrogen.

Your kernel has been around long enough that we should consider submitting it for brew.

I'm _so_ not looking forward to people saying anything about `curl`ing to bash, seems like the best way for now though.

**Comment by alexarchambault** [comment]
Ideally, I'd like the instructions to be something like
- install coursier,
- run `coursier launch jupyter-scala`.

[Aliases](https://github.com/coursier/coursier/issues/324#issuecomment-296481788) that may come in future versions of coursier should allow that. In the mean time, a bash script is almost required for the intricate coursier command that the kernel needs.

**Comment by jzf2101** [comment]
I'd use BeakerX to take care of this FWIW

**Comment by rgbkrk** [comment]
BeakerX uses a [custom kernelspecmanager](https://github.com/twosigma/beakerx/blob/b35392c0b41b135fbcf0ce31af4eaccf31ab1eb4/beakerx/beakerx/install.py#L165) which means that it doesn't work on nteract desktop (since we init with js).

**Comment by willingc** [comment]
Mention a scala kernel.
- [ ] Revisit the best way to present this for users to try without install due to the installation complexity (i.e. binder?)
- [ ] Document how to install scala kernel and use with nteract desktop

**Comment by alexarchambault** [comment]
About almond on binder, [this repository](https://github.com/sbrunk/almond-examples) already has a setup for that (cc @sbrunk).

About its install, its latest installation instructions as of writing this are available [here](http://almond-sh.github.io/almond/0.2.0/docs/quick-start-install). The command it mentions requires to have coursier, which one can get e.g. via `curl -L -o coursier https://git.io/coursier && chmod +x coursier` on OS X and Linux.

**Comment by jzf2101** [comment]
FWIW beaker-x has a bunch of JVM kernels as well?

**Comment by rgbkrk** [comment]
Last I checked, beakerx's JVM backed kernels required a separate kernelspec manager which was incompatible with how we adhere to the `kernel.json` format so that we can launch via node (in electron) on the desktop app.

**Comment by jzf2101** [comment]
Ah ok too bad

**Comment by willingc** [comment]
I updated the [almond install docs](https://almond-sh.github.io/almond/docs/next/quick-start-install) today. I think that we can get a Scala example up now. 
cc/ @mpacer @rgbkrk @alexarchambault

**Comment by alexarchambault** [comment]
Updated link for the [almond install docs](https://almond-sh.github.io/almond/docs/quick-start-install). (Might change again in the future, I'm in the midst of changing the CI scripts that update the website, and setting up a domain name for it.)
