### ISSUE TITLE
No <title> element on /desktop

### ISSUE THREAD

**Issue by aidan-fitz** [nteract/nteract.io#139]
The page `/desktop` does not contain a `<title>` element.

**Comment by captainsafia** [comment]
Thanks for reporting this, @aidan-fitz! Would you be interested in submitting a pull request to fix this? I’m happy to help you with it.

**Comment by aidan-fitz** [comment]
I started looking into the source code, too. Sure, I'd be happy to work on this.

**Comment by captainsafia** [comment]
Great! Let me know if you need any help with it. You’re welcome to join the nteract slack to get help at slack.nteract.io.
