### ISSUE TITLE
Typo in Components page

### ISSUE THREAD

**Issue by scizzorz** [nteract/nteract.io#163]
https://components.nteract.io/#source

Under the "Bring your own editor" subheader:

> You can **ass** React component(s)...

I tried to find where the text was stored in the repo so I could open a PR, but couldn't find it anywhere.

**Comment by captainsafia** [comment]
Hello @scizzorz! Thanks for opening this issue. A similar one was opened in https://github.com/nteract/nteract/issues/4262.

The typo was fixed but the docs page has yet to be deployed to production. I'll deploy it today.

In the meantime, I'll close this issue as we are tracking it in the issue linked above. Thanks for the sharp eye and the report!
