### ISSUE TITLE
Rendering of About page on IPad is wonky

### ISSUE THREAD

**Issue by willingc** [nteract/nteract.io#17]
- large white space in first section
- contributors gets cut off at about 1/2 the people and unable to scroll for rest

**Comment by rgbkrk** [comment]
Confirmed, also bad on iPhone.

**Comment by aulneau** [comment]
Will check out tomorrow!

**Comment by IonicaBizau** [comment]
From a quick look this happens because of `flex: 1`. It's buggy on desktop Safari too.

**Comment by IonicaBizau** [comment]
By removing [this line](https://github.com/nteract/nteract.io/blob/20707394c57dfaec6b28101684fbfd8fa63f3e6f/components/content-section/content-section.scss#L7) the white space is fixed, and by making [`.person`](https://github.com/nteract/nteract.io/blob/20707394c57dfaec6b28101684fbfd8fa63f3e6f/components/layout/layout.scss#L97)'s `width: 100%` on mobile the other issue is fixed.

I'm not confident if this is the right way to solve it, tho. I can open a pull request if you agree with this approach. 😁

**Comment by rgbkrk** [comment]
Sounds like a good fix for now, PR welcome.
