### ISSUE TITLE
404 - nteract.io/kernels node, scala, R, C++

### ISSUE THREAD

**Issue by LadyNaggaga** [nteract/nteract.io#196]
[404 Response](https://nteract.io/kernels/cplusplus) on all kernel documentation except python.  
![image](https://user-images.githubusercontent.com/2546640/63035831-d7184600-be89-11e9-886f-a3ba5afe09de.png)

**Comment by wadethestealth** [comment]
Can reproduce

**Comment by motin** [comment]
To clarify, when being on https://nteract.io/kernels and clicking on eg Node.js briefly shows the real Node.js kernel site while still on https://nteract.io/kernels, but then the URL switches over to https://nteract.io/kernels/node which yields 404.

**Comment by hjtoh** [comment]
I got the same problem, it's just annoying.

**Comment by ethanminfang** [comment]
Got the same problem for Julia. And I don't know how to add julia to the language mapping yet...

**Comment by captainsafia** [comment]
I've submitted a fix for this at https://github.com/nteract/nteract.io/pull/201.
