### ISSUE TITLE
Kernel options hidden behind terminal

### ISSUE THREAD

**Issue by bolariin** [nteract/nteract.io#216]
It looks like some kernel options are hidden behind the terminal image on the kernels page. You see the bug, if you visit https://nteract.io/kernels and reduce the screen width to about 800px.

I was able to reproduce on both Chrome and Firefox.

**Screenshot of the bug**
![bug on nteract kernels page ](https://user-images.githubusercontent.com/24629960/71850950-717c5e80-30a3-11ea-869d-ba3115b7467a.png)

**Comment by willingc** [comment]
If you experience this behavior, use a wider screen size for the browser.

**Comment by captainsafia** [comment]
Yeah, we have some CSS that wraps the kernel buttons so that they aren't hidden behind the terminal window. We might need to fix the cut-off width before wrapping starts.
