### ISSUE TITLE
nteract.io and nteract.github.io are different

### ISSUE THREAD

**Issue by kylebarron** [nteract/nteract.io#51]
Note that `nteract.github.io` doesn't have "Desktop", "Atom", "Kernels" links.

`nteract.io`:
![image](https://user-images.githubusercontent.com/15164633/45935768-adf27c80-bf7c-11e8-9477-5546ded97ebb.png)

`nteract.github.io`:
![image](https://user-images.githubusercontent.com/15164633/45935772-be0a5c00-bf7c-11e8-8bc1-b2b350cf3a46.png)

**Comment by kylebarron** [comment]
If we're not using Github Pages anymore, it seems preferable to turn off `nteract.github.io`, or better, redirect it to `nteract.io`.

**Comment by rgbkrk** [comment]
Yeah I agree, we should redirect nteract.github.io to nteract.io. I'd love someone to take that one. Client side redirect seems par for the course.

**Comment by kelleyblackmore** [comment]
Fixed for now. http://nteract.github.io/

**Comment by rgbkrk** [comment]
Awesome thanks!
