### ISSUE TITLE
Add links from nteract.io to documentation sites

### ISSUE THREAD

**Issue by kylebarron** [nteract/nteract.io#52]
From `https://nteract.io/atom` it would be great if there were a link to the Hydrogen documentation website `https://nteract.gitbooks.io/hydrogen/`. Currently I have to remember to go to the Github repo to find the link on the Readme.

I'm less sure about this but it might also be useful for `https://nteract.io/desktop` to have a link to something like `https://components.nteract.io/`?

**Comment by rgbkrk** [comment]
Yes please!
