### ISSUE TITLE
Fix desktop page

### ISSUE THREAD

**Issue by jdetle** [nteract/nteract.io#58]
nteract.io:

<img width="1552" alt="screen shot 2018-10-17 at 4 50 17 pm" src="https://user-images.githubusercontent.com/836375/47122696-c4fb5600-d22c-11e8-83d1-711f33d8d20d.png">

This PR:

<img width="1552" alt="screen shot 2018-10-17 at 4 49 57 pm" src="https://user-images.githubusercontent.com/836375/47122686-b319b300-d22c-11e8-9fe8-0e015c993aeb.png">

(Pardon the little 1.00 on the screen there, that's a chrome extension for video speed controller)

Anywho, I say this is fit to ship. Let's go for it!

_Originally posted by @rgbkrk in https://github.com/nteract/nteract.io/pull/54#issuecomment-430828250_

**Comment by rgbkrk** [comment]
Perfect, thanks! cc @doraf

**Comment by jdetle** [comment]
@doraf, I believe the fix is to make the image in the `desktop` page use the `CutoffImage` component, but I'm not sure.

**Comment by rgbkrk** [comment]
If that component works I think it's ok to just pave ahead with it. 😄
