### ISSUE TITLE
Add circle ci

### ISSUE THREAD

**Issue by jdetle** [nteract/nteract.io#61]
Need Circle CI for testing and typing. Can set it up following the steps here: https://circleci.com/setup-project/gh/nteract/nteract.io

**Comment by grabartley** [comment]
Hey I'm interested in setting this up but the link for set up steps requires a login

**Comment by rgbkrk** [comment]
Yeahhh CI usually isn't a new contributor friendly task. 😅

**Comment by rgbkrk** [comment]
We can find some other up-for-grabs items for you though @grabartley!

**Comment by lgeiger** [comment]
I tried to setup Azure Pipelines but I don't have the right permissions to do so.

**Comment by lgeiger** [comment]
Closed by #78
