### ISSUE TITLE
Use Specific Styled Component for Kernel Info

### ISSUE THREAD

**Issue by jdetle** [nteract/nteract.io#64]
Convert kernels section to use the components created in the /components route. This enables us to present richer data in the kernels page.

**Comment by willingc** [comment]
Hi @jdetle, Can this be closed? It looks done. However, I may not be correctly interpreting your message above ;-) Thanks.

**Comment by jdetle** [comment]
Not yet unfortunately, there is a much richer migration that I should do. But this is a good reminder to do it. Thanks @willingc.

**Comment by jdetle** [comment]
It looks like someone already got to this
