### ISSUE TITLE
Fix next.js title error

### ISSUE THREAD

**Issue by lgeiger** [nteract/nteract.io#76]
When running the site, next.js throws the following warning:
`Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title`

It looks like our Next.js setup can be greatly simplified since we're now fully on styled-components

**Comment by willingc** [comment]
Is this still an issue @lgeiger? I'm not seeing any warnings in my console.

**Comment by lgeiger** [comment]
You're right the warning is gone 👍
