### ISSUE TITLE
Prefetch over http for https version.

### ISSUE THREAD

**Issue by Carreau** [nteract/nteract.io#8]
Loading over https can be slow as Chrome complains: 

> Mixed Content: The page at 'https://nteract.io/' was loaded over HTTPS, but requested an insecure prefetch resource 'http://nteract.io/'. This content should also be served over HTTPS.

and indeed

```
  <!-- Prefetching, preloading, prebrowsing -->
  <link rel="dns-prefetch" href="//nteract.io/">
  <link rel="preconnect" href="http://nteract.io/">
  <link rel="prefetch" href="http://nteract.io/">
  <link rel="prerender" href="http://nteract.io/">
  <link rel="subresource" href="/assets/stylesheets/main.css">
```

Though I haven't found this in the source code.

**Comment by rgbkrk** [comment]
I've fixed that in the current refactor PR (https://github.com/nteract/nteract.io/pull/7) though it's ok to fix the current version here since it may not get finished and deployed until this weekend.

**Comment by rgbkrk** [comment]
Fixed in https://github.com/nteract/nteract.github.io/commit/6deb5584d5a4b27a141e274f0790440de5fb8489
